React1 week1
oyelajakenny/react1 pull request #1
Opened 2024-10-08 15:20 UTC by oyelajakenny

All tasks has been completed

2024-10-10 12:17 UTC, vdaguenet requested changes

2024-10-10 12:17 UTC, vdaguenet commented on app/about_us/page.js
You need to extract OurValues, OurCrew and OurPartners to their own files. This file is way too long.

2024-10-10 12:17 UTC, vdaguenet commented on app/about_us/page.js
> +        {" "}
You don't need these extra spaces

2024-10-11 09:07 UTC, oyelajakenny commented on app/about_us/page.js
Thank you for your feedback @vdaguenet, I have now made those changes

2024-10-14 13:47 UTC, vdaguenet approved these changes

2024-10-15 10:59 UTC, merged